name: angular_dart_test
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  angular: ^6.0.1
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
